// Datos del plan: ejercicios, días, cardio, alimentos y comidas.
// Imágenes y nombres: guías de Simply Fitness (https://www.simplyfitness.com/es/pages/workout-exercise-guides)

const IMG = 'https://cdn.shopify.com/s/files/1/0269/5551/3900/files/';
const GUIDE = 'https://www.simplyfitness.com/es/pages/';

// inc: tipo de incremento -> bar (barra, +2,5 kg), db (mancuerna, +2 kg), mq (máquina/polea, +2,5 kg), bw (peso corporal, reps), time (segundos)
// main: ejercicio básico de fuerza (calentamiento completo). warm: 1 serie de aproximación.
// rightFirst: unilateral, empieza SIEMPRE por el derecho e iguala reps con el izquierdo.
// extraRight: aislamiento SOLO brazo derecho (asimetría pectoral).
const EX = {
  'barbell-bench-press': { name: 'Press de banca con barra', img: 'Barbell-Bench-Press_0316b783-43b2-44f8-8a2b-b177a2cfcbfc_600x600.png', inc: 'bar', main: true, startKg: 30,
    start: 'Antes movías 40 kg. Semana 1: trabaja con 30 kg y deja que la app suba desde ahí.',
    note: 'Escápulas juntas y hacia abajo, pies firmes en el suelo. Baja controlado hasta rozar el esternón y empuja explosivo.' },
  'wide-grip-pulldown': { name: 'Jalón con agarre ancho', img: 'Wide-Grip-Pulldown_91fcba9b-47a2-4185-b093-aa542c81c55c_600x600.png', inc: 'mq', warm: true,
    note: 'Pecho arriba, tira llevando los codos hacia los bolsillos. Agarre ancho = espalda ancha (V).' },
  'incline-dumbbell-bench-press': { name: 'Press banca inclinado con mancuernas', img: 'Incline-Dumbbell-Bench-Press_c2bf89a2-433f-4a8f-9801-67c679980867_600x600.png', inc: 'db', rightFirst: true,
    note: 'Banco a 30°. A una mano: todas las reps con el DERECHO primero y luego el izquierdo hace exactamente las mismas, ni una más.' },
  'seated-cable-row': { name: 'Remo en máquina', img: 'Seated-Cable-Row_9470fa48-f0d1-40b1-a980-caee9e6f2e53_600x600.png', inc: 'mq',
    note: 'Pecho fuera, lleva el agarre al ombligo y aprieta las escápulas 1 segundo atrás.' },
  'dumbbell-lateral-raise': { name: 'Elevación lateral con mancuernas', img: 'Dumbbell-Lateral-Raise_31c81eee-81c4-4ffe-890d-ee13dd5bbf20_600x600.png', inc: 'db',
    note: 'Sube con los codos, no con las manos, hasta la altura del hombro. Sin balanceo: peso ligero y controlado, baja en 2 s.' },
  'cable-crossover': { name: 'Cruce de poleas', img: 'Cable-Crossover_09c90616-2777-47ed-927e-d5987edfce09_600x600.png', inc: 'mq', extraRight: true,
    note: 'SOLO brazo DERECHO. Cruza la mano por delante del cuerpo hasta pasar la línea media y aprieta el pecho 2 s.' },
  'cable-rope-puschdown': { name: 'Extensión de tríceps en polea con cuerda', img: 'Cable-Rope-Pushdown_600x600.png', inc: 'mq',
    note: 'Codos pegados al cuerpo y quietos. Abre la cuerda abajo y estira del todo.' },
  'reverse-barbell-curl': { name: 'Curl de barra invertido', img: 'Reverse-Barbell-Curl_600x600.png', inc: 'bar',
    note: 'Agarre con los nudillos hacia arriba. Trabaja la parte superior del antebrazo. Superserie con el siguiente (sin descanso entre ambos).' },
  'seated-barbell-wrist-curl': { name: 'Curl de muñeca con barra sentado', img: 'Seated-Barbell-Wrist-Curl_600x600.png', inc: 'bar',
    note: 'Antebrazos apoyados en los muslos, solo se mueve la muñeca. Deja rodar la barra hasta los dedos y cierra fuerte.' },
  'squat': { name: 'Sentadilla', img: 'Squat_d752e42d-02ba-4692-b300-c6e67ad5a4f5_600x600.png', inc: 'bar', main: true,
    start: 'Semana 1: busca un peso con el que harías 8-9 reps aunque solo hagas 5. Mejor quedarte corto.',
    note: 'Coge aire y bloquea el abdomen antes de bajar. Rodillas en la línea de la punta del pie, baja hasta muslo paralelo.' },
  'leg-press': { name: 'Prensa de piernas', img: 'Leg-Press_f7febd5c-75e5-42f4-9bb4-c938969ce293_600x600.png', inc: 'mq', warm: true,
    note: 'Pies a la anchura de hombros. No despegues el culo del respaldo ni bloquees las rodillas arriba.' },
  'dumbbell-stiff-leg-deadlift': { name: 'Peso muerto rumano con mancuernas', img: 'Dumbbell-Romanian-Deadlift_35135213-e0df-4ef2-b093-22ed8d04dc41_600x600.png', inc: 'db',
    note: 'Cadera atrás, espalda neutra, mancuernas rozando las piernas. Baja hasta notar estiramiento fuerte en el femoral.' },
  'leg-extension': { name: 'Extensión de piernas', img: 'Leg-Extension_41d91d3f-4b9c-4374-82e2-1d697ce35fe4_600x600.png', inc: 'mq',
    note: 'Pausa de 1 s arriba con el cuádriceps apretado. Baja en 2 s.' },
  'lying-leg-curl': { name: 'Curl de pierna tumbado', img: 'Lying-Leg-Curl_203153d8-79dd-4bb9-9125-708aa4327107_600x600.png', inc: 'mq',
    note: 'Cadera pegada al banco. Sube rápido, baja lento.' },
  'standing-calf-raise': { name: 'Elevación de gemelos de pie', img: 'Standing-Calf-Raise_61746b47-98aa-49ee-bb97-5a19562592b9_600x600.png', inc: 'mq',
    note: 'Pausa de 1 s abajo bien estirado y 1 s arriba de puntillas. Sin rebotes.' },
  'hanging-leg-raise': { name: 'Elevación de piernas colgado', img: 'Hanging-Leg-Raise_36986393-d0a6-494a-981f-4ea06a99b0b5_600x600.png', inc: 'bw',
    note: 'Sin balanceo, enrolla la pelvis hacia arriba. Si aún no puedes con las piernas rectas, sube rodillas al pecho.' },
  'barbell-row': { name: 'Remo con barra', img: 'Barbell-Row_4beb1d94-bac9-4538-9578-2d9cf93ef008_600x600.png', inc: 'bar', main: true,
    start: 'Semana 1: empieza con la barra + 10 kg por lado y sube si la técnica es limpia.',
    note: 'Torso a 45°, espalda neutra. Tira de la barra al ombligo con los codos, no con los bíceps.' },
  'dumbbell-shoulder-press': { name: 'Press de hombro con mancuernas', img: 'Dumbbell-Shoulder-Press_da0aa742-620a-45f7-9277-78137d38ff28_600x600.png', inc: 'db', warm: true,
    note: 'Sentado con respaldo. Baja hasta la altura de las orejas, sube sin chocar las mancuernas.' },
  'pull-up': { name: 'Elevaciones en barra fija (dominadas)', img: 'Pull-Up_600x600.png', inc: 'bw',
    note: 'Si no llegas a 6 reps, usa la máquina de dominadas asistida (apunta los kg de ayuda en negativo, ej. -20). Barbilla por encima de la barra.' },
  'dumbbell-bench-press': { name: 'Press de banca con mancuernas', img: 'Dumbbell-Bench-Press_13090f67-ccfc-4f3a-9bab-e75d753fa9fa_600x600.png', inc: 'db', rightFirst: true,
    note: 'A una mano: todas las reps con el DERECHO primero y luego el izquierdo hace exactamente las mismas. El otro brazo sujeta la mancuerna en el pecho.' },
  'cable-one-arm-lateral-raise': { name: 'Elevación lateral con cable a una mano', img: 'Cable-One-Arm-Lateral-Raise_3e57189f-cdf3-46ee-9a89-6ca054eae56a_600x600.png', inc: 'mq',
    note: 'Polea abajo, cable por delante del cuerpo. La tensión constante del cable hace crecer el hombro lateral = efecto viga.' },
  'high-cable-rear-delt-fly': { name: 'Cruces inversos en polea alta', img: 'High-Cable-Rear-Delt-Fly_600x600.png', inc: 'mq',
    note: 'Hombro posterior: da anchura vista de lado y de espalda. Brazos casi rectos, abre hacia atrás sin juntar escápulas.' },
  'peck-deck': { name: 'Aperturas en máquina Peck Deck', img: 'Peck-Deck_600x600.png', inc: 'mq', extraRight: true,
    note: 'SOLO brazo DERECHO. Cierra hasta el centro y aprieta el pecho 2 s. Peso con el que controles cada rep.' },
  'hammer-curl': { name: 'Curl martillo con mancuernas', img: 'Hammer-Curl_da9fea8b-fc81-4a4f-9af1-aea1b85239d7_600x600.png', inc: 'db',
    note: 'Agarre neutro (pulgar arriba). Trabaja el braquiorradial: es lo que hace grueso el antebrazo.' },
  'seated-barbell-wrist-extension': { name: 'Extensión de muñeca con barra sentado', img: 'Seated-Barbell-Wrist-Extension_600x600.png', inc: 'bar',
    note: 'Palmas hacia abajo, antebrazos en los muslos. Recorrido completo, lento. Usa poco peso.' },
  'barbell-deadlift': { name: 'Peso muerto con barra', img: 'Barbell-Deadlift_600x600.png', inc: 'bar', main: true,
    start: 'Semana 1: técnica antes que peso. Empieza con 60 kg o menos y sube solo si la espalda sale neutra.',
    note: 'Barra pegada a la espinilla, espalda neutra, aire y abdomen bloqueado. Empuja el suelo con las piernas y bloquea con glúteo.' },
  'bodyweight-bulgarian-split-squat': { name: 'Sentadilla búlgara', img: 'Bodyweight-Bulgarian-Split-Squat_600x600.png', inc: 'db', warm: true,
    note: 'Pie de atrás en un banco. Reps por pierna. Empieza sin peso; los kg son por mancuerna cuando las añadas.' },
  'barbell-hip-thrust': { name: 'Elevaciones de cadera con barra (hip thrust)', img: 'Barbell-Hip-Thrust_600x600.png', inc: 'bar',
    note: 'Espalda alta en el banco, barbilla al pecho. Aprieta glúteo 1 s arriba sin arquear la zona lumbar.' },
  'seated-leg-curl': { name: 'Curl de piernas sentado', img: 'Seated-Leg-Curl_e367789a-bbb3-4144-a926-5a9b42afc278_600x600.png', inc: 'mq',
    note: 'Inclínate un poco hacia delante para estirar más el femoral. Baja lento.' },
  'seated-calf-raise': { name: 'Elevación de gemelos sentado', img: 'Seated-Calf-Raise_8c8641b2-10f2-4dc8-9adb-8d80fd1a16d0_600x600.png', inc: 'mq',
    note: 'Recorrido completo con pausa abajo. Trabaja el sóleo (gemelo ancho).' },
  'rope-ab-pulldown': { name: 'Abdominales con cuerda en polea alta', img: 'Rope-Ab-Pulldown_b808db26-a4f3-4018-8007-5e31da5736dc_600x600.png', inc: 'mq',
    note: 'De rodillas, enrolla la columna llevando los codos a las rodillas. No tires con los brazos.' },
  'plank': { name: 'Plancha', img: 'Plank_3a82d566-9cb2-4c20-b301-bc8bd635c4d1_600x600.png', inc: 'time',
    note: 'Cuerpo recto, aprieta glúteo y abdomen como si te fueran a dar un golpe. Las "reps" son segundos.' },
  'ez-barbell-curl': { name: 'Curl con barra EZ', img: 'EZ-Barbell-Curl_42cb566b-6415-4318-94e0-c93f4b442e59_600x600.png', inc: 'bar',
    note: 'Codos quietos a los lados, sin impulso de cadera. Baja en 2-3 s.' },
  'dumbbell-overhead-triceps-extension': { name: 'Extensión de tríceps por encima de la cabeza', img: 'Dumbbell-Overhead-Triceps-Extension_99242f13-ab4d-4e77-be12-e0f180cc93ac_600x600.png', inc: 'db',
    note: 'Una mancuerna con las dos manos. Baja detrás de la cabeza estirando bien la cabeza larga del tríceps.' },
  'incline-dumbbell-curl': { name: 'Curl inclinado con mancuernas', img: 'Incline-Dumbbell-Curl_7debf468-cd34-49bc-8933-7f4b087e6cca_600x600.png', inc: 'db',
    note: 'Banco a 45-60°, brazos colgando por detrás del cuerpo. Gran estiramiento del bíceps.' },
};

// Cada ejercicio del día: [slug, series, repMin, repMax, descanso(s), etiquetas]
const DAYS = [
  { id: 'd1', short: 'D1', title: 'Torso A', sub: 'Fuerza pecho · espalda ancha · hombro', cardio: 'intervalos', ex: [
    ['barbell-bench-press', 4, 5, 6, 150, ['Fuerza', 'Pecho']],
    ['wide-grip-pulldown', 3, 8, 10, 90, ['Viga', 'Espalda']],
    ['incline-dumbbell-bench-press', 3, 8, 10, 90, ['Pecho', 'Dcho primero']],
    ['seated-cable-row', 3, 10, 12, 90, ['Espalda']],
    ['dumbbell-lateral-raise', 4, 12, 15, 60, ['Viga']],
    ['cable-crossover', 2, 12, 15, 60, ['Extra pecho dcho']],
    ['cable-rope-puschdown', 3, 10, 12, 60, ['Tríceps']],
    ['reverse-barbell-curl', 3, 12, 15, 30, ['Antebrazo']],
    ['seated-barbell-wrist-curl', 3, 15, 20, 60, ['Antebrazo']],
  ]},
  { id: 'd2', short: 'D2', title: 'Pierna A', sub: 'Fuerza sentadilla · cuádriceps', cardio: 'inclinada', ex: [
    ['squat', 4, 5, 6, 180, ['Fuerza', 'Pierna']],
    ['leg-press', 3, 10, 12, 120, ['Pierna']],
    ['dumbbell-stiff-leg-deadlift', 3, 8, 10, 120, ['Femoral']],
    ['leg-extension', 3, 12, 15, 60, ['Cuádriceps']],
    ['lying-leg-curl', 3, 10, 12, 60, ['Femoral']],
    ['standing-calf-raise', 3, 12, 15, 60, ['Gemelo']],
    ['hanging-leg-raise', 3, 10, 12, 60, ['Core']],
  ]},
  { id: 'd3', short: 'D3', title: 'Torso B', sub: 'Fuerza remo · densidad espalda · hombro', cardio: 'intervalos', ex: [
    ['barbell-row', 4, 6, 8, 150, ['Fuerza', 'Espalda']],
    ['dumbbell-shoulder-press', 3, 8, 10, 120, ['Hombro']],
    ['pull-up', 3, 6, 10, 120, ['Viga', 'Espalda']],
    ['dumbbell-bench-press', 3, 8, 10, 90, ['Pecho', 'Dcho primero']],
    ['cable-one-arm-lateral-raise', 4, 12, 15, 60, ['Viga']],
    ['high-cable-rear-delt-fly', 3, 12, 15, 60, ['Viga']],
    ['peck-deck', 2, 12, 15, 60, ['Extra pecho dcho']],
    ['hammer-curl', 3, 10, 12, 60, ['Antebrazo', 'Bíceps']],
    ['seated-barbell-wrist-extension', 3, 15, 20, 60, ['Antebrazo']],
  ]},
  { id: 'd4', short: 'D4', title: 'Pierna B', sub: 'Fuerza peso muerto · glúteo · core', cardio: 'inclinada', ex: [
    ['barbell-deadlift', 3, 4, 5, 180, ['Fuerza', 'Cadena posterior']],
    ['bodyweight-bulgarian-split-squat', 3, 8, 10, 90, ['Pierna']],
    ['barbell-hip-thrust', 3, 8, 10, 120, ['Glúteo']],
    ['seated-leg-curl', 3, 10, 12, 60, ['Femoral']],
    ['seated-calf-raise', 3, 15, 20, 60, ['Gemelo']],
    ['rope-ab-pulldown', 3, 12, 15, 60, ['Core']],
    ['plank', 3, 30, 60, 60, ['Core']],
  ]},
  { id: 'd5', short: 'D5', title: 'Opcional', sub: 'Hombro · brazos · antebrazo (con compañía)', cardio: 'libre', optional: true, ex: [
    ['dumbbell-lateral-raise', 4, 12, 15, 60, ['Viga']],
    ['high-cable-rear-delt-fly', 3, 12, 15, 60, ['Viga']],
    ['ez-barbell-curl', 3, 8, 10, 90, ['Bíceps']],
    ['dumbbell-overhead-triceps-extension', 3, 10, 12, 90, ['Tríceps']],
    ['incline-dumbbell-curl', 3, 10, 12, 60, ['Bíceps']],
    ['cable-rope-puschdown', 3, 12, 15, 60, ['Tríceps']],
    ['reverse-barbell-curl', 3, 12, 15, 30, ['Antebrazo']],
    ['seated-barbell-wrist-curl', 3, 15, 20, 60, ['Antebrazo']],
  ]},
];

// Cardio en cinta según semana del plan. FC zona 2 ≈ 110-135 ppm (Watch: Correr en interior → zonas de FC).
const CARDIO = {
  intervalos: [
    { weeks: [1, 2], title: 'Cinta · caminar + trote', lines: ['5 min caminata rápida (6 km/h)', '6 × [1 min trote suave 7,5-8 km/h + 2 min caminata 6 km/h]', '3 min caminata suave', 'Total ≈ 26 min'] },
    { weeks: [3, 4], title: 'Cinta · más trote', lines: ['5 min caminata rápida', '6 × [2 min trote 8 km/h + 1,5 min caminata]', '3 min suave', 'Total ≈ 29 min'] },
    { weeks: [5, 6], title: 'Cinta · bloques largos', lines: ['5 min caminata rápida', '3 × [5 min trote 8-8,5 km/h + 2 min caminata]', '3 min suave', 'Total ≈ 29 min'] },
    { weeks: [7, 99], title: 'Cinta · trote continuo', lines: ['5 min caminata rápida', '20 min trote continuo 8-9 km/h en zona 2', '3 min suave', 'Si ya es fácil: +1 km/h el último bloque de 5 min'] },
  ],
  inclinada: [
    { weeks: [1, 99], title: 'Cinta inclinada (sin impacto tras pierna)', lines: ['Inclinación 8-10 %, velocidad 5-5,5 km/h', '20-25 min sin agarrarte a la barandilla', 'Zona 2: deberías poder hablar en frases', 'Cada 2 semanas: +1 % de inclinación (máx. 12 %)'] },
  ],
  libre: [
    { weeks: [1, 99], title: 'Cardio opcional', lines: ['Si hay tiempo: 20 min de cinta inclinada (8-10 %, 5 km/h)', 'O la sesión de intervalos de los días de torso'] },
  ],
};

// Alimentos por 100 g (o 100 ml). u: [etiqueta de unidad, gramos por unidad]. drinks: consumiciones de alcohol por unidad.
const FOODS = [
  // Desayuno
  ['Huevo frito / revuelto', 180, 13.6, 0.8, 13.5, ['huevo', 50]],
  ['Huevo cocido', 143, 12.6, 0.7, 9.5, ['huevo', 50]],
  ['Pan blanco / de molde', 265, 9, 49, 3.2, ['rebanada', 30]],
  ['Arepa de maíz', 220, 4.5, 45, 2, ['arepa', 80]],
  ['Cereal de desayuno', 380, 7, 80, 3, ['bol 40 g', 40]],
  ['ColaCao', 375, 6, 77, 3.6, ['cucharada', 9]],
  ['Leche sin lactosa semidesnatada', 46, 3.2, 4.7, 1.6, ['vaso 250 ml', 250]],
  ['Proteína en polvo (batido)', 380, 78, 6, 5, ['cacito', 30]],
  ['Clara de huevo', 52, 11, 0.7, 0.2, ['clara', 33]],
  ['Pan 100% integral', 247, 13, 41, 3.4, ['rebanada', 35]],
  ['Bebida de soja sin azúcar', 33, 3.3, 0.5, 1.8, ['vaso 250 ml', 250]],
  ['Bebida de avena', 45, 0.8, 7, 1.5, ['vaso 250 ml', 250]],
  ['Cacao puro desgrasado', 350, 21, 13, 11, ['cucharada', 10]],
  ['Copos de avena', 379, 13, 67, 6.5, ['puñado 40 g', 40]],
  ['Proteína vegetal en polvo (guisante)', 380, 80, 5, 6, ['cacito', 30]],
  ['Café solo / té', 2, 0.1, 0, 0, ['taza', 100]],
  // Fruta
  ['Plátano / banano', 89, 1.1, 23, 0.3, ['ud', 120]],
  ['Manzana', 52, 0.3, 14, 0.2, ['ud', 180]],
  ['Naranja', 47, 0.9, 12, 0.1, ['ud', 200]],
  ['Kiwi', 61, 1.1, 15, 0.5, ['ud', 75]],
  ['Fresas', 32, 0.7, 7.7, 0.3, ['bol', 150]],
  ['Arándanos', 57, 0.7, 14, 0.3, ['puñado', 80]],
  // Proteína
  ['Pechuga de pollo (cruda)', 110, 23, 0, 1.5, ['filete', 150]],
  ['Contramuslo de pollo sin piel (crudo)', 121, 20, 0, 4.5, ['pieza', 100]],
  ['Pechuga de pavo (cruda)', 105, 24, 0, 1, ['filete', 150]],
  ['Lomo de cerdo (crudo)', 150, 21, 0, 7, ['filete', 120]],
  ['Ternera magra (cruda)', 120, 22, 0, 3.5, ['filete', 150]],
  ['Carne picada ternera 5 % (cruda)', 137, 21, 0, 5, ['ración', 150]],
  ['Merluza (cruda)', 80, 17, 0, 1, ['filete', 150]],
  ['Bacalao fresco (crudo)', 82, 18, 0, 0.7, ['filete', 150]],
  ['Salmón (crudo)', 208, 20, 0, 13, ['lomo', 150]],
  ['Gambas / langostinos (crudos)', 85, 20, 0, 0.5, ['ración', 150]],
  ['Mejillones (carne)', 86, 12, 3.7, 2.2, ['ración', 120]],
  ['Pulpo cocido', 82, 15, 2.2, 1, ['ración', 150]],
  ['Atún al natural (escurrido)', 110, 25, 0, 1, ['lata', 60]],
  ['Atún en aceite (escurrido)', 198, 26, 0, 10, ['lata', 60]],
  ['Jamón serrano', 240, 30, 0, 13, ['loncha', 15]],
  ['Fiambre de pavo (sin lactosa)', 105, 18, 2, 2, ['loncha', 15]],
  // Comida de casa (ya cocinada)
  ['Filete de res (cocinado)', 200, 30, 0, 9, ['filete', 120]],
  ['Chuleta / carne de cerdo (cocinada)', 230, 27, 0, 13, ['chuleta', 120]],
  ['Colombina de pollo (muslo, sin hueso)', 215, 27, 0, 11, ['colombina', 75]],
  ['Presa de pollo (cocinada)', 190, 28, 0, 8, ['presa', 100]],
  ['Albóndiga casera', 220, 14, 6, 15, ['albóndiga', 30]],
  ['Salchicha', 290, 12, 3, 26, ['ud', 50]],
  ['Tocino / panceta (frito)', 450, 18, 1, 42, ['loncha', 15]],
  ['Garbanzos guisados con salchicha', 150, 7, 15, 7, ['plato', 300]],
  ['Lentejas guisadas con salchicha', 130, 7, 14, 5, ['plato', 300]],
  ['Pasta con tocino', 210, 8, 28, 7, ['plato', 350]],
  ['Arroz blanco cocido (taza)', 130, 2.7, 28, 0.3, ['taza', 150]],
  ['Patata frita (sartén)', 312, 3.4, 41, 15, ['ración', 100]],
  ['Patata al horno / airfryer', 150, 3, 27, 3.5, ['ración', 150]],
  ['Maduro frito (plátano maduro)', 230, 1.5, 38, 9, ['medio maduro', 100]],
  ['Maduro al horno / airfryer', 140, 1.3, 33, 0.5, ['medio maduro', 100]],
  // Máquina del trabajo
  ['Máquina: frutos secos / cacahuetes', 600, 25, 15, 50, ['bolsa', 40]],
  ['Máquina: barrita de proteínas', 360, 33, 35, 12, ['barrita', 45]],
  ['Máquina: barrita de cereales', 400, 6, 70, 12, ['barrita', 25]],
  ['Máquina: patatas fritas / Doritos', 520, 6, 55, 30, ['bolsa', 40]],
  ['Máquina: chocolatina (KitKat, Twix, Snickers)', 500, 6, 60, 26, ['ud', 45]],
  ['Máquina: bollería (croissant, Bollycao)', 420, 7, 50, 21, ['ud', 60]],
  ['Máquina: galletas', 480, 6, 68, 20, ['paquete', 50]],
  ['Máquina: refresco normal', 42, 0, 10.6, 0, ['lata', 330]],
  // Carbohidrato
  ['Arroz blanco (crudo)', 360, 7, 79, 0.6, ['ración', 80]],
  ['Arroz cocido', 130, 2.7, 28, 0.3, ['plato', 200]],
  ['Arroz integral (crudo)', 362, 7.5, 76, 2.7, ['ración', 80]],
  ['Pasta integral (cruda)', 350, 13, 66, 2.5, ['ración', 80]],
  ['Patata (cruda)', 77, 2, 17, 0.1, ['ud mediana', 200]],
  ['Boniato (crudo)', 86, 1.6, 20, 0.1, ['ud', 250]],
  ['Quinoa (cruda)', 368, 14, 64, 6, ['ración', 70]],
  ['Lentejas cocidas', 116, 9, 20, 0.4, ['plato', 250]],
  ['Garbanzos cocidos', 140, 7.6, 22, 2.6, ['plato', 250]],
  // Verdura
  ['Ensalada (lechuga, tomate, cebolla)', 18, 1, 3.5, 0.2, ['bol', 200]],
  ['Brócoli', 34, 2.8, 7, 0.4, ['ración', 200]],
  ['Calabacín', 17, 1.2, 3.1, 0.3, ['ud', 250]],
  ['Pimiento', 26, 1, 6, 0.3, ['ud', 150]],
  ['Espárragos verdes', 20, 2.2, 3.9, 0.1, ['manojo', 200]],
  ['Judías verdes', 31, 1.8, 7, 0.2, ['ración', 200]],
  ['Espinacas', 23, 2.9, 3.6, 0.4, ['ración', 150]],
  ['Champiñones', 22, 3.1, 3.3, 0.3, ['ración', 150]],
  ['Crema de verduras casera sin lácteos', 40, 1.5, 6, 1, ['plato 300 ml', 300]],
  // Grasas
  ['Aceite de oliva virgen extra', 884, 0, 0, 100, ['cucharada', 10]],
  ['Aguacate', 160, 2, 8.5, 14.7, ['medio', 75]],
  ['Nueces', 654, 15, 14, 65, ['puñado', 20]],
  ['Almendras', 579, 21, 22, 50, ['puñado', 20]],
  ['Crema de cacahuete 100 %', 588, 25, 20, 50, ['cucharada', 15]],
  ['Chocolate negro 85 %', 600, 10, 20, 50, ['onza', 10]],
  // Bebidas
  ['Refresco zero / tónica zero', 1, 0, 0, 0, ['lata', 330]],
  ['Cerveza 0,0', 20, 0.3, 4.5, 0, ['tercio', 330]],
  ['Cerveza (caña)', 43, 0.4, 3.6, 0, ['caña', 200], 1],
  ['Cerveza (tercio)', 43, 0.4, 3.6, 0, ['tercio', 330], 1.5],
  ['Vino tinto / blanco seco', 83, 0.1, 2.6, 0, ['copa', 150], 1],
  ['Chupito (aguardiente, licor)', 250, 0, 10, 0, ['chupito', 40], 1],
  ['Cubata con refresco zero', 260, 0, 0, 0, ['cubata (50 ml destilado)', 50], 1.5],
];

// Tus comidas habituales con raciones ajustadas (≈2.000 kcal y ≈160 g proteína al día contando los 2 batidos).
// [nombre del alimento, gramos]
const PLAN_MEALS = {
  desayuno: { label: 'Desayuno · 10:00 (antes del gym)', opts: [
    { name: 'Huevos, pan y ColaCao', items: [['Huevo frito / revuelto', 100], ['Pan blanco / de molde', 60], ['Leche sin lactosa semidesnatada', 250], ['ColaCao', 18], ['Plátano / banano', 120]] },
    { name: 'Huevos y cereal', items: [['Huevo frito / revuelto', 100], ['Cereal de desayuno', 40], ['Leche sin lactosa semidesnatada', 250], ['Plátano / banano', 120]] },
    { name: 'Huevos con arepa', items: [['Huevo frito / revuelto', 100], ['Arepa de maíz', 80], ['Plátano / banano', 120]] },
  ]},
  batido: { label: 'Batido post-gym · 13:15', opts: [
    { name: 'Batido + creatina', items: [['Proteína en polvo (batido)', 30]] },
    { name: 'Batido + banano', items: [['Proteína en polvo (batido)', 30], ['Plátano / banano', 120]] },
  ]},
  almuerzo: { label: 'Almuerzo en casa · 13:45', opts: [
    { name: 'Arroz, carne y maduro', items: [['Arroz blanco cocido (taza)', 150], ['Filete de res (cocinado)', 150], ['Maduro frito (plátano maduro)', 100], ['Ensalada (lechuga, tomate, cebolla)', 150]] },
    { name: 'Arroz, 2 colombinas y patata', items: [['Arroz blanco cocido (taza)', 150], ['Colombina de pollo (muslo, sin hueso)', 150], ['Patata frita (sartén)', 100]] },
    { name: 'Albóndigas, arroz y patata', items: [['Albóndiga casera', 180], ['Arroz blanco cocido (taza)', 150], ['Patata frita (sartén)', 100]] },
    { name: 'Garbanzos con salchicha y arroz', items: [['Garbanzos guisados con salchicha', 300], ['Arroz blanco cocido (taza)', 100], ['Huevo cocido', 50]] },
    { name: 'Lentejas con salchicha y arroz', items: [['Lentejas guisadas con salchicha', 300], ['Arroz blanco cocido (taza)', 100], ['Huevo cocido', 50]] },
    { name: 'Pasta con tocino', items: [['Pasta con tocino', 350], ['Atún al natural (escurrido)', 60]] },
  ]},
  merienda: { label: 'Merienda en el trabajo · 18:00', opts: [
    { name: '2º batido (shaker de casa)', items: [['Proteína en polvo (batido)', 30]] },
    { name: 'Atún con pan', items: [['Atún al natural (escurrido)', 60], ['Pan blanco / de molde', 60]] },
    { name: 'Máquina: frutos secos', items: [['Máquina: frutos secos / cacahuetes', 40]] },
    { name: 'Máquina: barrita proteica', items: [['Máquina: barrita de proteínas', 45]] },
  ]},
  cena: { label: 'Cena · 21:45 (al salir del trabajo)', opts: [
    { name: 'Atún con arroz', items: [['Atún al natural (escurrido)', 120], ['Arroz blanco cocido (taza)', 150], ['Aceite de oliva virgen extra', 5], ['Ensalada (lechuga, tomate, cebolla)', 100]] },
    { name: '3 huevos con pan', items: [['Huevo frito / revuelto', 150], ['Pan blanco / de molde', 60]] },
    { name: '3 huevos con arepa', items: [['Huevo frito / revuelto', 150], ['Arepa de maíz', 80]] },
  ]},
};

// Tu día tipo (gym 11-13, trabajo 15-21). [hora, qué, detalle]
const SCHEDULE = [
  ['09:30', 'Levántate', 'Vaso grande de agua. Mismo horario también los días sin gym.'],
  ['10:00', 'Desayuno', 'Huevos + pan, arepa o cereal + banano. Energía para entrenar.'],
  ['11:00', 'Gym', 'Pesas + cinta. Lleva 1 L de agua.'],
  ['13:15', 'Batido + creatina', '1 cacito de proteína + 5 g de creatina en agua, al salir del gym.'],
  ['13:45', 'Almuerzo', 'Tu plato de casa con las raciones del "plato de entreno".'],
  ['15:00', 'Trabajo', 'Lleva el shaker con el polvo ya puesto y una fruta.'],
  ['18:00', 'Merienda', '2º batido (solo añades agua). Si es máquina: frutos secos o barrita proteica.'],
  ['21:45', 'Cena', 'Atún con arroz o 3 huevos con pan. Proteína primero.'],
  ['01:00', 'Dormir', '8 h de sueño: durmiendo poco la barriga baja mucho peor.'],
];
