// Datos del plan: ejercicios, días, cardio, alimentos y comidas.
// Imágenes y nombres: guías de Simply Fitness (https://www.simplyfitness.com/es/pages/workout-exercise-guides)

const IMG = 'https://cdn.shopify.com/s/files/1/0269/5551/3900/files/';
const GUIDE = 'https://www.simplyfitness.com/es/pages/';

// inc: tipo de incremento -> bar (barra, +2,5 kg), db (mancuerna, +2 kg), mq (máquina/polea, +2,5 kg), bw (peso corporal, reps), time (segundos)
// main: ejercicio básico de fuerza (calentamiento completo). warm: 1 serie de aproximación.
// rightFirst: unilateral, empieza SIEMPRE por el derecho e iguala reps con el izquierdo.
// extraRight: aislamiento SOLO brazo derecho (asimetría pectoral).
const EX = {
  'barbell-bench-press': { name: 'Press de banca con barra', img: 'Barbell-Bench-Press_0316b783-43b2-44f8-8a2b-b177a2cfcbfc_600x600.png', inc: 'bar', main: true, startKg: 30,
    start: 'Antes movías 40 kg. Semana 1: trabaja con 30 kg y deja que la app suba desde ahí.',
    note: 'Escápulas juntas y hacia abajo, pies firmes en el suelo. Baja controlado hasta rozar el esternón y empuja explosivo.' },
  'wide-grip-pulldown': { name: 'Jalón con agarre ancho', img: 'Wide-Grip-Pulldown_91fcba9b-47a2-4185-b093-aa542c81c55c_600x600.png', inc: 'mq', warm: true,
    note: 'Pecho arriba, tira llevando los codos hacia los bolsillos. Agarre ancho = espalda ancha (V).' },
  'incline-dumbbell-bench-press': { name: 'Press banca inclinado con mancuernas', img: 'Incline-Dumbbell-Bench-Press_c2bf89a2-433f-4a8f-9801-67c679980867_600x600.png', inc: 'db', rightFirst: true,
    note: 'Banco a 30°. A una mano: todas las reps con el DERECHO primero y luego el izquierdo hace exactamente las mismas, ni una más.' },
  'seated-cable-row': { name: 'Remo en máquina', img: 'Seated-Cable-Row_9470fa48-f0d1-40b1-a980-caee9e6f2e53_600x600.png', inc: 'mq',
    note: 'Pecho fuera, lleva el agarre al ombligo y aprieta las escápulas 1 segundo atrás.' },
  'dumbbell-lateral-raise': { name: 'Elevación lateral con mancuernas', img: 'Dumbbell-Lateral-Raise_31c81eee-81c4-4ffe-890d-ee13dd5bbf20_600x600.png', inc: 'db',
    note: 'Sube con los codos, no con las manos, hasta la altura del hombro. Sin balanceo: peso ligero y controlado, baja en 2 s.' },
  'cable-crossover': { name: 'Cruce de poleas', img: 'Cable-Crossover_09c90616-2777-47ed-927e-d5987edfce09_600x600.png', inc: 'mq', extraRight: true,
    note: 'SOLO brazo DERECHO. Cruza la mano por delante del cuerpo hasta pasar la línea media y aprieta el pecho 2 s.' },
  'cable-rope-puschdown': { name: 'Extensión de tríceps en polea con cuerda', img: 'Cable-Rope-Pushdown_600x600.png', inc: 'mq',
    note: 'Codos pegados al cuerpo y quietos. Abre la cuerda abajo y estira del todo.' },
  'reverse-barbell-curl': { name: 'Curl de barra invertido', img: 'Reverse-Barbell-Curl_600x600.png', inc: 'bar',
    note: 'Agarre con los nudillos hacia arriba. Trabaja la parte superior del antebrazo. Superserie con el siguiente (sin descanso entre ambos).' },
  'seated-barbell-wrist-curl': { name: 'Curl de muñeca con barra sentado', img: 'Seated-Barbell-Wrist-Curl_600x600.png', inc: 'bar',
    note: 'Antebrazos apoyados en los muslos, solo se mueve la muñeca. Deja rodar la barra hasta los dedos y cierra fuerte.' },
  'squat': { name: 'Sentadilla', img: 'Squat_d752e42d-02ba-4692-b300-c6e67ad5a4f5_600x600.png', inc: 'bar', main: true,
    start: 'Semana 1: busca un peso con el que harías 8-9 reps aunque solo hagas 5. Mejor quedarte corto.',
    note: 'Coge aire y bloquea el abdomen antes de bajar. Rodillas en la línea de la punta del pie, baja hasta muslo paralelo.' },
  'leg-press': { name: 'Prensa de piernas', img: 'Leg-Press_f7febd5c-75e5-42f4-9bb4-c938969ce293_600x600.png', inc: 'mq', warm: true,
    note: 'Pies a la anchura de hombros. No despegues el culo del respaldo ni bloquees las rodillas arriba.' },
  'dumbbell-stiff-leg-deadlift': { name: 'Peso muerto rumano con mancuernas', img: 'Dumbbell-Romanian-Deadlift_35135213-e0df-4ef2-b093-22ed8d04dc41_600x600.png', inc: 'db',
    note: 'Cadera atrás, espalda neutra, mancuernas rozando las piernas. Baja hasta notar estiramiento fuerte en el femoral.' },
  'leg-extension': { name: 'Extensión de piernas', img: 'Leg-Extension_41d91d3f-4b9c-4374-82e2-1d697ce35fe4_600x600.png', inc: 'mq',
    note: 'Pausa de 1 s arriba con el cuádriceps apretado. Baja en 2 s.' },
  'lying-leg-curl': { name: 'Curl de pierna tumbado', img: 'Lying-Leg-Curl_203153d8-79dd-4bb9-9125-708aa4327107_600x600.png', inc: 'mq',
    note: 'Cadera pegada al banco. Sube rápido, baja lento.' },
  'standing-calf-raise': { name: 'Elevación de gemelos de pie', img: 'Standing-Calf-Raise_61746b47-98aa-49ee-bb97-5a19562592b9_600x600.png', inc: 'mq',
    note: 'Pausa de 1 s abajo bien estirado y 1 s arriba de puntillas. Sin rebotes.' },
  'hanging-leg-raise': { name: 'Elevación de piernas colgado', img: 'Hanging-Leg-Raise_36986393-d0a6-494a-981f-4ea06a99b0b5_600x600.png', inc: 'bw',
    note: 'Sin balanceo, enrolla la pelvis hacia arriba. Si aún no puedes con las piernas rectas, sube rodillas al pecho.' },
  'barbell-row': { name: 'Remo con barra', img: 'Barbell-Row_4beb1d94-bac9-4538-9578-2d9cf93ef008_600x600.png', inc: 'bar', main: true,
    start: 'Semana 1: empieza con la barra + 10 kg por lado y sube si la técnica es limpia.',
    note: 'Torso a 45°, espalda neutra. Tira de la barra al ombligo con los codos, no con los bíceps.' },
  'dumbbell-shoulder-press': { name: 'Press de hombro con mancuernas', img: 'Dumbbell-Shoulder-Press_da0aa742-620a-45f7-9277-78137d38ff28_600x600.png', inc: 'db', warm: true,
    note: 'Sentado con respaldo. Baja hasta la altura de las orejas, sube sin chocar las mancuernas.' },
  'pull-up': { name: 'Elevaciones en barra fija (dominadas)', img: 'Pull-Up_600x600.png', inc: 'bw',
    note: 'Si no llegas a 6 reps, usa la máquina de dominadas asistida (apunta los kg de ayuda en negativo, ej. -20). Barbilla por encima de la barra.' },
  'dumbbell-bench-press': { name: 'Press de banca con mancuernas', img: 'Dumbbell-Bench-Press_13090f67-ccfc-4f3a-9bab-e75d753fa9fa_600x600.png', inc: 'db', rightFirst: true,
    note: 'A una mano: todas las reps con el DERECHO primero y luego el izquierdo hace exactamente las mismas. El otro brazo sujeta la mancuerna en el pecho.' },
  'cable-one-arm-lateral-raise': { name: 'Elevación lateral con cable a una mano', img: 'Cable-One-Arm-Lateral-Raise_3e57189f-cdf3-46ee-9a89-6ca054eae56a_600x600.png', inc: 'mq',
    note: 'Polea abajo, cable por delante del cuerpo. La tensión constante del cable hace crecer el hombro lateral = efecto viga.' },
  'high-cable-rear-delt-fly': { name: 'Cruces inversos en polea alta', img: 'High-Cable-Rear-Delt-Fly_600x600.png', inc: 'mq',
    note: 'Hombro posterior: da anchura vista de lado y de espalda. Brazos casi rectos, abre hacia atrás sin juntar escápulas.' },
  'peck-deck': { name: 'Aperturas en máquina Peck Deck', img: 'Peck-Deck_600x600.png', inc: 'mq', extraRight: true,
    note: 'SOLO brazo DERECHO. Cierra hasta el centro y aprieta el pecho 2 s. Peso con el que controles cada rep.' },
  'hammer-curl': { name: 'Curl martillo con mancuernas', img: 'Hammer-Curl_da9fea8b-fc81-4a4f-9af1-aea1b85239d7_600x600.png', inc: 'db',
    note: 'Agarre neutro (pulgar arriba). Trabaja el braquiorradial: es lo que hace grueso el antebrazo.' },
  'seated-barbell-wrist-extension': { name: 'Extensión de muñeca con barra sentado', img: 'Seated-Barbell-Wrist-Extension_600x600.png', inc: 'bar',
    note: 'Palmas hacia abajo, antebrazos en los muslos. Recorrido completo, lento. Usa poco peso.' },
  'barbell-deadlift': { name: 'Peso muerto con barra', img: 'Barbell-Deadlift_600x600.png', inc: 'bar', main: true,
    start: 'Semana 1: técnica antes que peso. Empieza con 60 kg o menos y sube solo si la espalda sale neutra.',
    note: 'Barra pegada a la espinilla, espalda neutra, aire y abdomen bloqueado. Empuja el suelo con las piernas y bloquea con glúteo.' },
  'bodyweight-bulgarian-split-squat': { name: 'Sentadilla búlgara', img: 'Bodyweight-Bulgarian-Split-Squat_600x600.png', inc: 'db', warm: true,
    note: 'Pie de atrás en un banco. Reps por pierna. Empieza sin peso; los kg son por mancuerna cuando las añadas.' },
  'barbell-hip-thrust': { name: 'Elevaciones de cadera con barra (hip thrust)', img: 'Barbell-Hip-Thrust_600x600.png', inc: 'bar',
    note: 'Espalda alta en el banco, barbilla al pecho. Aprieta glúteo 1 s arriba sin arquear la zona lumbar.' },
  'seated-leg-curl': { name: 'Curl de piernas sentado', img: 'Seated-Leg-Curl_e367789a-bbb3-4144-a926-5a9b42afc278_600x600.png', inc: 'mq',
    note: 'Inclínate un poco hacia delante para estirar más el femoral. Baja lento.' },
  'seated-calf-raise': { name: 'Elevación de gemelos sentado', img: 'Seated-Calf-Raise_8c8641b2-10f2-4dc8-9adb-8d80fd1a16d0_600x600.png', inc: 'mq',
    note: 'Recorrido completo con pausa abajo. Trabaja el sóleo (gemelo ancho).' },
  'rope-ab-pulldown': { name: 'Abdominales con cuerda en polea alta', img: 'Rope-Ab-Pulldown_b808db26-a4f3-4018-8007-5e31da5736dc_600x600.png', inc: 'mq',
    note: 'De rodillas, enrolla la columna llevando los codos a las rodillas. No tires con los brazos.' },
  'plank': { name: 'Plancha', img: 'Plank_3a82d566-9cb2-4c20-b301-bc8bd635c4d1_600x600.png', inc: 'time',
    note: 'Cuerpo recto, aprieta glúteo y abdomen como si te fueran a dar un golpe. Las "reps" son segundos.' },
  'ez-barbell-curl': { name: 'Curl con barra EZ', img: 'EZ-Barbell-Curl_42cb566b-6415-4318-94e0-c93f4b442e59_600x600.png', inc: 'bar',
    note: 'Codos quietos a los lados, sin impulso de cadera. Baja en 2-3 s.' },
  'dumbbell-overhead-triceps-extension': { name: 'Extensión de tríceps por encima de la cabeza', img: 'Dumbbell-Overhead-Triceps-Extension_99242f13-ab4d-4e77-be12-e0f180cc93ac_600x600.png', inc: 'db',
    note: 'Una mancuerna con las dos manos. Baja detrás de la cabeza estirando bien la cabeza larga del tríceps.' },
  'incline-dumbbell-curl': { name: 'Curl inclinado con mancuernas', img: 'Incline-Dumbbell-Curl_7debf468-cd34-49bc-8933-7f4b087e6cca_600x600.png', inc: 'db',
    note: 'Banco a 45-60°, brazos colgando por detrás del cuerpo. Gran estiramiento del bíceps.' },
  // Nuevos y alternativas
  'close-grip-pulldown': { name: 'Jalón al pecho con agarre cerrado', img: 'Close-Grip-Pulldown_072bb5ce-e3d9-4007-b8d2-d343e9d1051b_600x600.png', inc: 'mq',
    note: 'Agarre estrecho (triángulo), tira al pecho con los codos pegados. Densidad de espalda.' },
  'hack-squat': { name: 'Sentadilla hack', img: 'Hack-Squat_044b3d09-ffa7-4728-b56f-f4fb3c175548_600x600.png', inc: 'mq', warm: true,
    note: 'Espalda pegada al respaldo, baja hasta muslo paralelo o algo más. Pies a media altura de la plataforma.' },
  'smith-machine-shoulder-press': { name: 'Press de hombros en multipower', img: 'Smith-Machine-Shoulder-Press_e53bea60-c273-41e9-a70d-f5fa339c6780_600x600.png', inc: 'bar', warm: true,
    note: 'Barra guiada: seguro aunque llegues cansado. Banco casi vertical, baja hasta la barbilla y gira los ganchos al acabar.' },
  'chest-press-machine': { name: 'Press de pecho en máquina', img: 'Chest-Press-Machine_ab8cd29d-5698-4110-a938-098bda19b5fc_600x600.png', inc: 'mq', rightFirst: true,
    note: 'Si los brazos de la máquina son independientes, empieza por el DERECHO y el izquierdo iguala. Si no, empuja pensando en apretar el pecho derecho.' },
  'bent-over-lateral-raise': { name: 'Pájaros con mancuernas', img: 'Bent-Over-Lateral-Raise_41bd4de4-0370-4e6b-9501-37cdcc26ded4_600x600.png', inc: 'db',
    note: 'Hombro posterior: da anchura vista de lado y de espalda. Torso inclinado, abre los brazos hacia los lados sin juntar escápulas. Alternativa: contractora sentado al revés.' },
  'crunch-machine': { name: 'Abdominales en máquina', img: 'Crunch-Machine_538b22a3-379f-4a45-874a-ec1d798235b4_600x600.png', inc: 'mq',
    note: 'Enrolla la columna llevando el pecho a la cadera. Pausa 1 s abajo apretando. No tires con los brazos.' },
  'dumbbell-bent-over-row-single-arm': { name: 'Remo con mancuerna a una mano', img: 'Dumbbell-Bent-Over-Row-_Single-Arm_49867db3-f465-4fbc-b359-29cbdda502e2_600x600.png', inc: 'db', warm: true,
    note: 'Rodilla y mano en el banco, espalda plana. Lleva la mancuerna hacia la cadera, no al hombro.' },
  'triceps-pressdown': { name: 'Extensión de tríceps en polea (barra)', img: 'Triceps-Pressdown_e759437b-6200-4b44-b484-14db770024a4_600x600.png', inc: 'mq',
    note: 'Codos pegados al cuerpo y quietos. Estira del todo abajo y sube controlado.' },
  'single-arm-cable-triceps-extension': { name: 'Extensión de tríceps con cable a una mano', img: 'Single-Arm-Cable-Triceps-Extension_600x600.png', inc: 'mq',
    note: 'Un brazo cada vez, codo fijo. Empieza por el derecho.' },
  't-bar-rows': { name: 'Remo en barra T', img: 'T-Bar-Rows_600x600.png', inc: 'bar',
    note: 'Pecho apoyado si la máquina lo tiene. Tira con los codos pegados al cuerpo.' },
  'front-squat': { name: 'Sentadilla frontal', img: 'Front-Squat_600x600.png', inc: 'bar',
    note: 'Barra sobre los hombros delanteros, codos altos. Torso muy vertical.' },
  'trap-bar-deadlift': { name: 'Peso muerto con barra hexagonal', img: 'Trap-Bar-Deadlift_600x600.png', inc: 'bar', main: true,
    note: 'Más amable con la espalda que el peso muerto normal. Empuja el suelo y bloquea con glúteo.' },
  'lunge': { name: 'Zancada', img: 'Lunge_600x600.png', inc: 'db',
    note: 'Paso largo, rodilla de atrás casi al suelo. Reps por pierna, con mancuernas cuando la domines.' },
  'barbell-stiff-leg-deadlift': { name: 'Peso muerto rumano con barra', img: 'Barbell-Romanian-Deadlift_34ede1b4-63ac-451d-9536-bbf9942b560c_600x600.png', inc: 'bar', warm: true,
    note: 'Cadera atrás, barra pegada a las piernas, espalda neutra. Baja hasta notar estiramiento fuerte en el femoral.' },
  'single-leg-extension': { name: 'Extensión de cuádriceps a una pierna', img: 'Single-Leg-Extension_9cf850d1-0b9b-4fb3-8caf-49d438e86db0_600x600.png', inc: 'mq',
    note: 'Una pierna cada vez, pausa arriba.' },
  'standing-knee-raise': { name: 'Elevación de rodillas en paralelas', img: 'Standing-Knee-Raise_600x600.png', inc: 'bw',
    note: 'Espalda pegada al respaldo, sube rodillas al pecho enrollando la pelvis.' },
  'reverse-grip-pulldown': { name: 'Jalón al pecho con agarre invertido', img: 'Reverse-Grip-Pulldown_10c5341f-30fd-4126-8fd7-2fa05c079889_600x600.png', inc: 'mq',
    note: 'Palmas hacia ti, tira al pecho con los codos hacia abajo. Trabaja también bíceps.' },
  'rope-cable-curl': { name: 'Curl con cuerda en polea', img: 'Rope-Cable-Curl_6216e254-5f77-462c-9954-ea210fff8a70_600x600.png', inc: 'mq',
    note: 'Agarre neutro como el martillo: bíceps + antebrazo con tensión constante.' },
  'dumbbell-concentration-curl': { name: 'Curl concentrado con mancuerna', img: 'Dumbbell-Concentration-Curl_289b5739-4bdd-40e6-a195-6ecfcc685126_600x600.png', inc: 'db',
    note: 'Codo apoyado en el muslo, sube lento y aprieta arriba. Empieza por el derecho.' },
  'incline-barbell-bench-press': { name: 'Press de banca inclinado con barra', img: 'Incline-Barbell-Bench-Press_dc0c6279-d038-44f5-a682-54c2a5e2602c_600x600.png', inc: 'bar',
    note: 'Banco a 30°. Baja a la parte alta del pecho. Con barra no puedes empezar por el derecho: piensa en empujar con él.' },
  'parallel-dip-bar': { name: 'Fondos en paralelas', img: 'Parallel-Dip-Bar_600x600.png', inc: 'bw',
    note: 'Pecho y tríceps a la vez. Baja hasta que el brazo quede paralelo al suelo. Si no llegas a 6, usa la máquina asistida (kg en negativo).' },
  'bench-dips': { name: 'Fondos en banco', img: 'Bench-Dips_600x600.png', inc: 'bw',
    note: 'Manos en el banco detrás de ti, baja doblando codos. Más fácil que en paralelas.' },
  'close-grip-bench-press': { name: 'Press banca con agarre cerrado', img: 'Close-Grip-Bench-Press_28c01bfb-504d-43a6-8264-bd2101d317b9_600x600.png', inc: 'bar',
    note: 'Manos a la anchura de hombros, codos pegados. Tríceps fuerte. Con barra en rack.' },
  'straight-arm-lat-pulldown': { name: 'Jalón dorsal con brazos rectos', img: 'Straight-Arm-Lat-Pulldown_600x600.png', inc: 'mq',
    note: 'Brazos casi rectos, baja la barra hasta los muslos con el dorsal. Ancho de espalda.' },
};

// Semana fija (5 días). Cada ejercicio: [slug, series, repMin, repMax, descanso(s), etiquetas, alternativas]
// Los básicos (main) suben a +1 serie desde la semana 3.
// Regla de seguridad: los press con mancuernas por encima de la cara van siempre de primeros.
const DAYS = [
  { id: 'd1', short: 'D1', title: 'Torso fuerza', wd: 'Lunes', wdn: 1, sub: 'Press banca · remo · hombro · bíceps y tríceps', cardio: 'intervalos', shoes: 'run', ex: [
    ['barbell-bench-press', 3, 5, 6, 150, ['Fuerza', 'Pecho'], ['dumbbell-bench-press', 'chest-press-machine']],
    ['barbell-row', 3, 6, 8, 150, ['Fuerza', 'Espalda'], ['t-bar-rows', 'dumbbell-bent-over-row-single-arm']],
    ['smith-machine-shoulder-press', 3, 8, 10, 120, ['Hombro'], ['dumbbell-shoulder-press']],
    ['wide-grip-pulldown', 3, 8, 10, 90, ['Viga', 'Espalda'], ['close-grip-pulldown', 'pull-up']],
    ['dumbbell-lateral-raise', 3, 12, 15, 60, ['Viga'], ['cable-one-arm-lateral-raise']],
    ['cable-crossover', 2, 12, 15, 60, ['Extra pecho dcho'], ['peck-deck']],
    ['ez-barbell-curl', 3, 8, 10, 30, ['Bíceps', 'Superserie'], ['hammer-curl', 'rope-cable-curl']],
    ['cable-rope-puschdown', 3, 10, 12, 75, ['Tríceps', 'Superserie'], ['triceps-pressdown', 'single-arm-cable-triceps-extension']],
    ['reverse-barbell-curl', 2, 12, 15, 60, ['Antebrazo'], ['hammer-curl']],
  ]},
  { id: 'd2', short: 'D2', title: 'Pierna fuerza', wd: 'Martes', wdn: 2, sub: 'Sentadilla · rumano · prensa · gemelo · core', cardio: 'suave', shoes: 'flat', klass: 'Abdominales / Xpress (15 min) o Boxeo', ex: [
    ['squat', 3, 5, 6, 180, ['Fuerza', 'Pierna'], ['hack-squat', 'front-squat']],
    ['dumbbell-stiff-leg-deadlift', 3, 8, 10, 120, ['Femoral', 'Glúteo'], ['barbell-stiff-leg-deadlift']],
    ['leg-press', 3, 10, 12, 120, ['Pierna'], ['hack-squat']],
    ['leg-extension', 2, 12, 15, 60, ['Cuádriceps'], ['single-leg-extension']],
    ['standing-calf-raise', 3, 12, 15, 60, ['Gemelo'], ['seated-calf-raise']],
    ['hanging-leg-raise', 3, 10, 12, 60, ['Core'], ['standing-knee-raise', 'crunch-machine']],
  ]},
  { id: 'd3', short: 'D3', title: 'Tirón', wd: 'Jueves', wdn: 4, sub: 'Espalda · bíceps · antebrazo · hombro posterior', cardio: 'intervalos', shoes: 'run', ex: [
    ['pull-up', 3, 6, 10, 120, ['Viga', 'Espalda'], ['close-grip-pulldown', 'reverse-grip-pulldown']],
    ['dumbbell-bent-over-row-single-arm', 3, 8, 10, 90, ['Espalda'], ['t-bar-rows', 'seated-cable-row']],
    ['seated-cable-row', 3, 10, 12, 90, ['Espalda'], ['straight-arm-lat-pulldown', 't-bar-rows']],
    ['bent-over-lateral-raise', 3, 12, 15, 60, ['Viga'], ['high-cable-rear-delt-fly']],
    ['hammer-curl', 3, 10, 12, 60, ['Bíceps', 'Antebrazo'], ['rope-cable-curl']],
    ['incline-dumbbell-curl', 3, 10, 12, 60, ['Bíceps'], ['dumbbell-concentration-curl', 'ez-barbell-curl']],
    ['seated-barbell-wrist-curl', 3, 15, 20, 60, ['Antebrazo'], []],
  ]},
  { id: 'd4', short: 'D4', title: 'Empuje', wd: 'Viernes', wdn: 5, sub: 'Pecho · hombro · tríceps · pecho derecho', cardio: 'intervalos', shoes: 'run', ex: [
    ['incline-dumbbell-bench-press', 3, 8, 10, 120, ['Pecho', 'Dcho primero'], ['incline-barbell-bench-press']],
    ['chest-press-machine', 3, 10, 12, 90, ['Pecho', 'Dcho primero'], ['dumbbell-bench-press']],
    ['parallel-dip-bar', 3, 6, 10, 120, ['Tríceps', 'Pecho'], ['bench-dips', 'close-grip-bench-press']],
    ['cable-one-arm-lateral-raise', 4, 12, 15, 60, ['Viga'], ['dumbbell-lateral-raise']],
    ['peck-deck', 2, 12, 15, 60, ['Extra pecho dcho'], ['cable-crossover']],
    ['triceps-pressdown', 3, 10, 12, 60, ['Tríceps'], ['cable-rope-puschdown', 'single-arm-cable-triceps-extension']],
    ['seated-barbell-wrist-extension', 2, 15, 20, 60, ['Antebrazo'], []],
  ]},
  { id: 'd5', short: 'D5', title: 'Pierna + hombro', wd: 'Sábado', wdn: 6, sub: 'Peso muerto · hack · búlgara · femoral · viga', cardio: 'suave', shoes: 'flat', klass: 'Boxeo (con compañía) o Abdominales', ex: [
    ['barbell-deadlift', 3, 4, 5, 180, ['Fuerza', 'Cadena posterior'], ['trap-bar-deadlift']],
    ['hack-squat', 3, 8, 10, 120, ['Pierna'], ['leg-press', 'front-squat']],
    ['bodyweight-bulgarian-split-squat', 2, 8, 10, 90, ['Pierna', 'Glúteo'], ['lunge']],
    ['seated-leg-curl', 3, 10, 12, 60, ['Femoral'], ['lying-leg-curl']],
    ['seated-calf-raise', 3, 15, 20, 60, ['Gemelo'], ['standing-calf-raise']],
    ['dumbbell-lateral-raise', 3, 12, 15, 60, ['Viga'], ['cable-one-arm-lateral-raise']],
    ['crunch-machine', 3, 12, 15, 60, ['Core'], ['rope-ab-pulldown', 'plank']],
  ]},
];

// Cardio según semana del plan. FC zona 2 ≈ 110-135 ppm (Watch: Correr en interior → zonas de FC).
const CARDIO = {
  intervalos: [
    { weeks: [1, 2], title: '🏃 Correr en cinta · caminar + trote', lines: ['5 min caminata rápida (6 km/h)', '6 × [1 min trote suave 7,5-8 km/h + 2 min caminata 6 km/h]', '3 min caminata suave', 'Total ≈ 26 min'] },
    { weeks: [3, 4], title: '🏃 Correr en cinta · más trote', lines: ['5 min caminata rápida', '6 × [2 min trote 8 km/h + 1,5 min caminata]', '3 min suave', 'Total ≈ 29 min'] },
    { weeks: [5, 6], title: '🏃 Correr en cinta · bloques largos', lines: ['5 min caminata rápida', '3 × [5 min trote 8-8,5 km/h + 2 min caminata]', '3 min suave', 'Total ≈ 29 min'] },
    { weeks: [7, 99], title: '🏃 Correr en cinta · trote continuo', lines: ['5 min caminata rápida', '20 min trote continuo 8-9 km/h en zona 2', '3 min suave', 'Si ya es fácil: +1 km/h el último bloque de 5 min'] },
  ],
  suave: [
    { weeks: [1, 99], title: '🚶 Sin correr: recuperación', lines: ['10 min caminando en cinta a 5 km/h, sin inclinación', 'Ayuda a que las piernas se recuperen para el próximo día', 'Después, la clase si te apuntaste'] },
  ],
};

const SHOES = {
  run: '👟 Lleva zapatillas de correr (y si puedes, unas planas para las pesas)',
  flat: '🥿 Zapatillas de suela plana y dura (tipo Converse/Vans): nada de amortiguación para sentadilla y peso muerto',
};

// Alimentos por 100 g (o 100 ml), nombres de España (Mercadona).
// [nombre, kcal, proteína, hidratos, grasa, [unidad, gramos por unidad, paso del +/− (1 por defecto)], consumiciones de alcohol por unidad]
const FOODS = [
  // Desayuno
  ['Huevo frito o revuelto', 180, 13.6, 0.8, 13.5, ['huevo', 50]],
  ['Huevo cocido', 143, 12.6, 0.7, 9.5, ['huevo', 50]],
  ['Claras de huevo (botella)', 52, 11, 0.7, 0.2, ['vaso 100 ml', 100]],
  ['Pan de molde', 265, 9, 49, 3.2, ['rebanada', 30]],
  ['Pan de molde integral', 247, 13, 41, 3.4, ['rebanada', 30]],
  ['Pan de barra', 270, 9, 55, 1.5, ['trozo (¼ de barra)', 60]],
  ['Arepa de maíz', 220, 4.5, 45, 2, ['arepa', 80]],
  ['Cereales de desayuno', 380, 7, 80, 3, ['bol (40 g)', 40]],
  ['Copos de avena', 379, 13, 67, 6.5, ['puñado (40 g)', 40]],
  ['Leche sin lactosa semidesnatada', 46, 3.2, 4.7, 1.6, ['vaso', 250]],
  ['Bebida de soja', 33, 3.3, 0.5, 1.8, ['vaso', 250]],
  ['ColaCao', 375, 6, 77, 3.6, ['cucharada', 9]],
  ['Té o café (sin azúcar)', 1, 0, 0, 0, ['taza', 250]],
  ['Azúcar', 400, 0, 100, 0, ['cucharadita', 5]],
  ['Crema de cacahuete 100 %', 588, 25, 20, 50, ['cucharada', 15]],
  ['Pechuga de pavo en lonchas', 105, 18, 2, 2, ['loncha', 15]],
  // Fruta
  ['Plátano', 89, 1.1, 23, 0.3, ['plátano', 120]],
  ['Manzana', 52, 0.3, 14, 0.2, ['manzana', 180]],
  ['Mandarina', 53, 0.8, 13, 0.3, ['mandarina', 80]],
  ['Naranja', 47, 0.9, 12, 0.1, ['naranja', 200]],
  ['Kiwi', 61, 1.1, 15, 0.5, ['kiwi', 75]],
  ['Pera', 57, 0.4, 15, 0.1, ['pera', 170]],
  // Batido
  ['Proteína en polvo', 380, 78, 6, 5, ['cacito (30 g)', 30]],
  // Arroz, pasta y legumbres (cocinado)
  ['Arroz blanco cocido', 130, 2.7, 28, 0.3, ['taza', 150, 0.5]],
  ['Pasta cocida', 158, 5.8, 31, 0.9, ['plato', 200, 0.5]],
  ['Garbanzos guisados', 125, 6.5, 17, 3.5, ['cazo', 150]],
  ['Lentejas guisadas', 105, 7, 15, 2, ['cazo', 150]],
  ['Alubias guisadas', 110, 7, 15, 2.5, ['cazo', 150]],
  ['Garbanzos cocidos (bote)', 120, 7, 16, 2.5, ['medio bote', 200]],
  ['Lentejas cocidas (bote)', 100, 8, 14, 0.5, ['medio bote', 200]],
  // Acompañantes
  ['Patata cocida', 80, 2, 17, 0.1, ['patata', 150]],
  ['Patatas fritas (sartén)', 312, 3.4, 41, 15, ['ración', 100]],
  ['Patatas al horno o airfryer', 150, 3, 27, 3.5, ['ración', 150]],
  ['Plátano macho maduro frito', 230, 1.5, 38, 9, ['medio plátano', 100]],
  ['Ensalada (lechuga, tomate, cebolla)', 18, 1, 3.5, 0.2, ['bol', 150]],
  ['Tomate', 18, 0.9, 3.9, 0.2, ['tomate', 150]],
  ['Aguacate', 160, 2, 8.5, 14.7, ['medio', 75]],
  ['Aceite de oliva', 884, 0, 0, 100, ['cucharada', 10]],
  // Carne y pollo (cocinado)
  ['Pechuga de pollo', 165, 31, 0, 3.6, ['filete', 120]],
  ['Muslo de pollo (colombina)', 215, 27, 0, 11, ['muslo', 75]],
  ['Contramuslo de pollo', 210, 26, 0, 11, ['contramuslo', 90]],
  ['Alitas de pollo', 240, 24, 0, 16, ['alita', 35]],
  ['Pollo asado (sin piel)', 190, 28, 0, 8, ['ración', 150]],
  ['Carne picada', 250, 26, 0, 16, ['ración', 100]],
  ['Albóndigas', 220, 14, 6, 15, ['albóndiga', 30]],
  ['Filete de ternera', 200, 30, 0, 9, ['filete', 120]],
  ['Lomo de cerdo', 200, 29, 0, 9, ['filete', 100]],
  ['Chuleta de cerdo', 230, 27, 0, 13, ['chuleta', 120]],
  ['Panceta (frita)', 450, 18, 1, 42, ['tira', 25]],
  ['Salchicha', 290, 12, 3, 26, ['salchicha', 50]],
  ['Chorizo', 455, 24, 2, 39, ['trozo', 30]],
  // Latas y pescado
  ['Atún al natural', 110, 25, 0, 1, ['lata', 60]],
  ['Atún en aceite (escurrido)', 198, 26, 0, 10, ['lata', 60]],
  ['Sardinas en aceite (escurridas)', 210, 24, 0, 12.5, ['lata', 85]],
  ['Caballa en aceite (escurrida)', 230, 22, 0, 15, ['lata', 85]],
  ['Mejillones en escabeche', 140, 15, 4, 7, ['lata', 70]],
  ['Gambas cocidas', 95, 21, 0, 1, ['ración', 100]],
  // Merienda y máquina
  ['Barrita de proteínas', 360, 33, 35, 12, ['barrita', 45]],
  ['Frutos secos o cacahuetes', 600, 25, 15, 50, ['puñado / bolsa pequeña', 30]],
  ['Tortitas de maíz', 380, 8, 80, 3, ['tortita', 8]],
  ['Chocolate negro 85 %', 600, 10, 20, 50, ['onza', 10]],
  ['Máquina: barrita de cereales', 400, 6, 70, 12, ['barrita', 25]],
  ['Máquina: patatas fritas / Doritos', 520, 6, 55, 30, ['bolsa', 40]],
  ['Máquina: chocolatina (KitKat, Twix…)', 500, 6, 60, 26, ['chocolatina', 45]],
  ['Máquina: bollería (croissant, Bollycao)', 420, 7, 50, 21, ['bollo', 60]],
  ['Máquina: galletas', 480, 6, 68, 20, ['paquete', 50]],
  // Bebidas
  ['Refresco zero', 1, 0, 0, 0, ['lata', 330]],
  ['Refresco normal', 42, 0, 10.6, 0, ['lata', 330]],
  ['Cerveza 0,0', 20, 0.3, 4.5, 0, ['tercio', 330]],
  ['Cerveza (caña)', 43, 0.4, 3.6, 0, ['caña', 200], 1],
  ['Cerveza (tercio)', 43, 0.4, 3.6, 0, ['tercio', 330], 1.5],
  ['Vino', 83, 0.1, 2.6, 0, ['copa', 150], 1],
  ['Chupito (aguardiente, licor)', 250, 0, 10, 0, ['chupito', 40], 1],
  ['Cubata con refresco zero', 260, 0, 0, 0, ['cubata', 50], 1.5],
];

// Menú para ir añadiendo lo que comes en cada momento del día: [sección, [alimentos]]
const MENU = {
  desayuno: [
    ['Huevos y proteína', ['Huevo frito o revuelto', 'Huevo cocido', 'Claras de huevo (botella)', 'Pechuga de pavo en lonchas']],
    ['Pan y cereal', ['Pan de molde', 'Pan de molde integral', 'Pan de barra', 'Arepa de maíz', 'Cereales de desayuno', 'Copos de avena']],
    ['Para beber', ['Leche sin lactosa semidesnatada', 'Bebida de soja', 'ColaCao', 'Té o café (sin azúcar)', 'Azúcar']],
    ['Fruta y extras', ['Plátano', 'Manzana', 'Mandarina', 'Kiwi', 'Crema de cacahuete 100 %']],
  ],
  batido: [
    ['Batido post-gym', ['Proteína en polvo', 'Plátano', 'Leche sin lactosa semidesnatada', 'Bebida de soja', 'Copos de avena']],
  ],
  almuerzo: [
    ['Proteína', ['Muslo de pollo (colombina)', 'Contramuslo de pollo', 'Pechuga de pollo', 'Alitas de pollo', 'Carne picada', 'Albóndigas', 'Filete de ternera', 'Lomo de cerdo', 'Chuleta de cerdo', 'Salchicha', 'Panceta (frita)', 'Chorizo']],
    ['Tu kit extra (compensa la ración del piso)', ['Huevo cocido', 'Huevo frito o revuelto', 'Atún al natural', 'Sardinas en aceite (escurridas)', 'Pechuga de pavo en lonchas']],
    ['Arroz, pasta y legumbres', ['Arroz blanco cocido', 'Pasta cocida', 'Garbanzos guisados', 'Lentejas guisadas', 'Alubias guisadas']],
    ['Acompañantes', ['Patata cocida', 'Patatas fritas (sartén)', 'Patatas al horno o airfryer', 'Plátano macho maduro frito', 'Ensalada (lechuga, tomate, cebolla)', 'Tomate', 'Aguacate', 'Aceite de oliva', 'Pan de barra']],
    ['Bebida', ['Té o café (sin azúcar)', 'Azúcar', 'Refresco zero', 'Refresco normal']],
  ],
  merienda: [
    ['Lo ideal', ['Proteína en polvo', 'Plátano', 'Manzana', 'Mandarina', 'Huevo cocido', 'Atún al natural', 'Pan de molde']],
    ['Máquina del trabajo', ['Barrita de proteínas', 'Frutos secos o cacahuetes', 'Máquina: barrita de cereales', 'Máquina: patatas fritas / Doritos', 'Máquina: chocolatina (KitKat, Twix…)', 'Máquina: bollería (croissant, Bollycao)', 'Máquina: galletas', 'Refresco normal', 'Refresco zero']],
  ],
  cena: [
    ['Proteína', ['Atún al natural', 'Atún en aceite (escurrido)', 'Sardinas en aceite (escurridas)', 'Caballa en aceite (escurrida)', 'Mejillones en escabeche', 'Huevo frito o revuelto', 'Huevo cocido', 'Pollo asado (sin piel)', 'Pechuga de pollo', 'Gambas cocidas', 'Pechuga de pavo en lonchas']],
    ['Acompañante', ['Arroz blanco cocido', 'Pan de molde', 'Pan de barra', 'Arepa de maíz', 'Patata cocida', 'Ensalada (lechuga, tomate, cebolla)', 'Tomate', 'Aguacate', 'Aceite de oliva']],
    ['Para beber', ['Té o café (sin azúcar)', 'Leche sin lactosa semidesnatada', 'ColaCao']],
  ],
  extra: [
    ['Bebidas', ['Refresco zero', 'Refresco normal', 'Cerveza 0,0', 'Cerveza (caña)', 'Cerveza (tercio)', 'Vino', 'Chupito (aguardiente, licor)', 'Cubata con refresco zero']],
    ['Picoteo', ['Frutos secos o cacahuetes', 'Chocolate negro 85 %', 'Tortitas de maíz', 'Plátano', 'Manzana', 'Máquina: chocolatina (KitKat, Twix…)', 'Máquina: patatas fritas / Doritos']],
  ],
};

// Tu día tipo (gym 11-13, trabajo 15-21). [hora, qué, detalle]
const SCHEDULE = [
  ['09:30', 'Levántate', 'Vaso grande de agua. Mismo horario también los días sin gym.'],
  ['10:00', 'Desayuno', 'Huevos + pan, arepa o cereal + plátano. Energía para entrenar.'],
  ['11:00', 'Gym', 'Pesas + cinta. Lleva 1 L de agua.'],
  ['13:15', 'Batido + creatina', '1 cacito de proteína + 5 g de creatina en 300 ml de agua, todo junto.'],
  ['13:45', 'Almuerzo', 'Lo que toque en el piso + tu kit extra (huevo cocido o lata) si la proteína fue poca.'],
  ['15:00', 'Trabajo', 'Lleva una fruta y, por si acaso, el shaker con un cacito ya puesto.'],
  ['18:00', 'Merienda', 'Mira en la app cuánta proteína te falta: si son más de 40 g, 2º batido. Si no, fruta.'],
  ['21:45', 'Cena', 'Atún, sardinas o huevos con arroz o pan. Proteína primero.'],
  ['01:00', 'Dormir', '8 h de sueño: durmiendo poco la barriga baja mucho peor.'],
];
